import { 
  LayoutDashboard, 
  ShieldCheck, 
  BarChart3, 
  Settings, 
  Bell, 
  Search, 
  Plus,
  CheckCircle,
  XCircle,
  AlertCircle,
  Clock,
  ChevronRight,
  FileText,
  User,
  Video,
  Activity,
  LogOut,
  Menu,
  X,
  Bot,
  Sun,
  Moon
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Verifications: ShieldCheck,
  Reports: BarChart3,
  Settings: Settings,
  Bell: Bell,
  Search: Search,
  Plus: Plus,
  Check: CheckCircle,
  Reject: XCircle,
  Alert: AlertCircle,
  Clock: Clock,
  ChevronRight: ChevronRight,
  Document: FileText,
  User: User,
  Liveness: Video,
  Activity: Activity,
  Logout: LogOut,
  Menu: Menu,
  Close: X,
  AI: Bot,
  Sun: Sun,
  Moon: Moon
};